"""Markdown导出器 - 将数据导出为Markdown格式"""

import os
from datetime import datetime
from exporters.base import BaseExporter


class MarkdownExporter(BaseExporter):
    """Markdown格式导出器"""

    name = "markdown"
    extension = "md"

    def export(self, items, analysis=None, output_path=None, title="InsightHarvest Report", **kwargs):
        """
        导出为Markdown格式

        Args:
            items: 数据项列表
            analysis: 分析结果字典
            output_path: 输出文件路径
            title: 报告标题
        """
        if output_path is None:
            output_path = self._generate_filename("insight_harvest", "md")

        self._ensure_output_dir(output_path)

        lines = []

        # 标题
        lines.append("# {}\n".format(title))
        lines.append("> Generated by InsightHarvest-CLI | {}\n".format(
            datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        ))
        lines.append("")

        # 摘要统计
        if analysis:
            lines.append("## Summary\n")
            stats = analysis.get("statistics", {})
            lines.append("- **Total Items**: {}".format(analysis.get("total_items", 0)))
            lines.append("- **Total Score**: {}".format(stats.get("total_score", 0)))
            lines.append("- **Average Score**: {}".format(stats.get("avg_score", 0)))
            lines.append("")

            # 来源分布
            source_dist = analysis.get("source_distribution", {})
            if source_dist:
                lines.append("### Source Distribution\n")
                lines.append("| Source | Count |")
                lines.append("|--------|-------|")
                for source, count in sorted(source_dist.items(), key=lambda x: x[1], reverse=True):
                    lines.append("| {} | {} |".format(source, count))
                lines.append("")

            # 关键词
            keywords = kwargs.get("keywords", [])
            if keywords:
                lines.append("### Top Keywords\n")
                for kw in keywords[:15]:
                    lines.append("- **{}** (freq: {}, tfidf: {:.4f})".format(
                        kw.get("keyword", ""),
                        kw.get("frequency", 0),
                        kw.get("tfidf_score", 0),
                    ))
                lines.append("")

            # 热门条目
            top_items = analysis.get("top_items", [])
            if top_items:
                lines.append("### Top Items\n")
                for i, item in enumerate(top_items, 1):
                    lines.append("{}. **[{}]({})** (score: {}, source: {})".format(
                        i,
                        item.get("title", ""),
                        item.get("url", ""),
                        item.get("score", 0),
                        item.get("source", ""),
                    ))
                lines.append("")

        # 数据列表
        lines.append("## Collected Items\n")
        lines.append("")

        for i, item in enumerate(items, 1):
            lines.append("### {}. {}\n".format(i, item.get("title", "Untitled")))
            if item.get("url"):
                lines.append("**URL**: {}".format(item.get("url")))
            if item.get("source"):
                lines.append("**Source**: {}".format(item.get("source")))
            if item.get("author"):
                lines.append("**Author**: {}".format(item.get("author")))
            if item.get("score"):
                lines.append("**Score**: {}".format(item.get("score")))
            if item.get("description"):
                desc = item.get("description", "")
                if len(desc) > 300:
                    desc = desc[:300] + "..."
                lines.append("**Description**: {}".format(desc))
            if item.get("tags"):
                lines.append("**Tags**: {}".format(", ".join(item.get("tags"))))
            lines.append("")

        # LLM摘要
        llm_summary = kwargs.get("llm_summary", "")
        if llm_summary:
            lines.append("---\n")
            lines.append("## AI Analysis Summary\n")
            lines.append(llm_summary)
            lines.append("")

        content = "\n".join(lines)

        try:
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(content)
            if self.logger:
                self.logger.info("[export] Markdown报告已保存: {}".format(output_path))
        except (IOError, OSError) as e:
            if self.logger:
                self.logger.error("[export] 保存失败: {}".format(str(e)))

        return output_path
